apiVersion: v1
kind: Service
metadata:
    name: jenkins-service
    labels:
      app: jenkins
spec:
    selector:
        app: jenkins
    type: NodePort
    ports:
        -   nodePort: 30000
            port: 8080
            targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkinsmasterdeploy
spec:
    replicas: 1
    selector: 
        matchLabels:
            app: jenkins
      
    template:
        metadata: 
            name: master-pod1
            labels:
                app: jenkins
        spec: 
            containers: 
            -   name: master-con
                image: sainimac/kubejenkin:v1