apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: apache-claim
  labels:
    app: apache
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---

apiVersion: v1
kind: Service
metadata:
  name: apache-service
  labels:
    app: apache
spec:
  ports:
    - nodePort: 30001
      port: 80
      targetPort: 80
  selector:
    app: apache
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-pod
  labels:
    app: apache
spec:
  selector:
    matchLabels:
      app: apache
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
      - image: vimal13/apache-webserver-php
        name: apache
        ports:
        - containerPort: 30001
          name: apache
        volumeMounts:
        - name: apache-persistent-storage
          mountPath: /var/www/html
      volumes:
      - name: apache-persistent-storage 
        persistentVolumeClaim: