apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: php-claim
  labels:
    app: php
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---

apiVersion: v1
kind: Service
metadata:
  name: php-service
  labels:
    app: php
spec:
  ports:
    - nodePort: 30002
      port: 80
      targetPort: 80
  selector:
    app: php
  type: LoadBalancer
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-pod
  labels:
    app: php
spec:
  selector:
    matchLabels:
      app: php
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: php
    spec:
      containers:
      - image: vimal13/apache-webserver-php
        name: php
        ports:
        - containerPort: 30002
          name: php
        volumeMounts:
        - name: php-persistent-storage
          mountPath: /var/www/html
      volumes:
      - name: php-persistent-storage 
        persistentVolumeClaim:
          claimName: php-claim